version: "3.7"

services:

  api:
    build: ./api
    image: flask-skeleton
    container_name: flask-skeleton
    restart: always
    environment:
      - APP_NAME=Skeleton
    expose:
      - 8080

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: skeleton
    ports:
      - "27017:27017"